[package]
name = "salps"
version = "0.2.0"
edition = "2021"

description = "random string generator"

author = "parchment"
license = "MIT"
readme = "readme.md"
repository = "https://github.com/wainggan/salps"

[dependencies]
lykoi_data = "0.5.0"

